#%RAML 1.0
title: swiggy-customers-sapi-Teddy
baseUri: http://localhost:8081/api
mediaType: application/json
types:
  customer: !include datatypes/Customer.raml
traits:
  Pageable: !include traits/Pageable.raml
resourceTypes:
  collection: !include resources/collection.raml
  member: !include resources/member.raml


/customers:
  post:
    body:
        type: 
    responses:
      201:
        body:
            type: string
      409:
        body:
            type: string

      500:
        body:
            type: string
          
  get:
    is: [Pageable]
    description: Get All Customers
    
    responses:
      200:
        body:
            
      500:
        
            




                   
    
      
  

  
        
          