#%RAML 1.0
title: swiggy-customers-sapi-Teddy
baseUri: http://localhost:8081/api
mediaType: application/json
types:
  Customer: !include datatypes/Customer.raml
  CustomerRequest: !include datatypes/CustomerRequest.raml
  UpdateCustomerRequest: !include datatypes/UpdateCustomerRequest.raml
  Address: !include datatypes/Address.raml
  AddressRequest: !include datatypes/AddressRequest.raml
  
traits:
  Pageable: !include traits/Pageable.raml
resourceTypes:
  collection: !include resources/collection.raml
  member: !include resources/member.raml


/customers:
 
  type:
    collection
  get:
    is: [Pageable]
      
    responses:
      200:
        body:
          application/json:            
            type: Customer[]
  post: 
   
     
  /{id}:
    type:
      member
    get:  
    put:     

      
      
    /addresses:
      type:
        collection
      post: