#%RAML 1.0 NamedExample
CustomersExample:
  firstName: Teddy BallGame
  "lastName": "",
  "email": "",
  "phone": "",
  "addresses": [
    {
      "houseNumber": "",
      "street": "",
      "city": "",
      "pincode": "",
      "addressType": "billing"
    }
  ]
}
