#%RAML 1.0 NamedExample
CustomersExample:
  firstName: Teddy 
  lastName: Ballgame
  email: teddy.ballgame@gmail.com
  phone: "415-514-4154"
  addresses: 
  - houseNumber: 1000 
    street: Main Street
    city: Los Angeles 
    pincode: 021589
    addressType: delivery
  - houseNumber: 2000 
    street: Martin Square
    city: Los Angeles 
    pincode: 5646454
    addressType: billing

 