#%RAML 1.0 NamedExample
CustomersExample:
  firstName: Teddy 
  lastName: Ballgame
  email: teddy.ballgame@gmail.com
  phone: "415-514-4154"
  addresses: 
    houseNumber": "",
      "street": "",
      "city": "",
      "pincode": "",
      "addressType": "billing"
    }
  ]
}
