#%RAML 1.0 DataType
properties:
  CustomerfirstName: string
  CustomerlastName: string
  Customeremail: string
  Customerphone: integer
  address: !include Address.raml
  links: 
    type: array
    
    
examples: !include ../Examples/address.raml 

  example