#%RAML 1.0 DataType
properties:
  CustomerfirstName: string
  CustomerlastName: string
  Customeremail: 
  "phone": "",
  "addresses"
  address: !include Address.raml
  links: 
    type: array
    
    
examples: !include ../examples/customer.raml 

  example